/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:2e07fd2e-1057-42e7-84ec-be4c6896ed6e",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_es8qQWLS5",
    "aws_user_pools_web_client_id": "2bdkqttapmdq5tc7j75c5daafn",
    "oauth": {}
};


export default awsmobile;
